### ISSUE TITLE
newline constant in "embed" results an invalid json

### ISSUE THREAD

**Issue by thekjohn** [seraphx2/ado-discord-webhook#3]
The lack of escaping or extra formatting around pipeline variables like $(Build.SourceVersionMessage) breaks the embed json.

**Comment by seraphx2** [comment]
Can you provide an example? I am not sure what you mean since I'm not having a problem with this.

**Comment by thekjohn** [comment]
embed json:

[{
"title": "Build $(Build.BuildNumber) succeeded ($(Build.Reason))",
"description" : "$(Build.SourceVersionMessage)"
}]

the commit message (Build.SourceVersionMessage) was:

"add Get********* to user repository
separate permissions from role IDs in claim list
Update********** uses property group filtering
add ************* to UserAuthorization (and principal)"

**Comment by thekjohn** [comment]
did you managed to reproduce it? the problem is that after the replacement of $(Build.SourceVersionMessage) in the JSON, the value of "description" spawns through multiple lines.

You can check the first answer here: https://stackoverflow.com/questions/2392766/multiline-strings-in-json

**Comment by seraphx2** [comment]
sorry. I've been super busy. lol. umm. I'll see what I can do today.

**Comment by seraphx2** [comment]
Hey sorry. Life issues got in the way.
Finally took a look at this and I found an npm package that will convert the returns in multiline strings to `\r\n`.
Was able to unit test and verify behavior.
Is that what you want to happen?

**Comment by thekjohn** [comment]
Hi! I hope everything got resolved there!

About the issue: yes, I guess :)

**Comment by seraphx2** [comment]
so the only way I could test this was to create a multiline string with a string literal in JavaScript. unfortunately, that technically adds a \n on its own. so I am still not sure if the string generated in that build variable will work and I have no way in JavaScript to replicate a string like that that I know of.

I am probably going to have to update it live and see what happens (or make a "dev" marketplace entry I guess).

**Comment by thekjohn** [comment]
good to hear! is there any ETA for a release?

**Comment by thekjohn** [comment]
accidentally closed...

**Comment by seraphx2** [comment]
I might be able to today.

**Comment by thekjohn** [comment]
Sadly I see no commit nor VS Marketplace release. Is there any chance for a release sometimes?

**Comment by seraphx2** [comment]
Done

**Comment by thekjohn** [comment]
still failure

**commit message**
"just some cleanup
so I can write multiple comment lines
so I can test the new discord announcer fix"

**YAML task:**

steps:
- task: robmburke.ado-discord-webhook.custom-build-release-task.ado-discord-webhook@1
  displayName: ci
  inputs:
    channelId: xxx
    webhookKey: xxx
    name: '$(Build.DefinitionName)'
    messageType: embeds
    embeds: |
     [{
     "title": "Build $(Build.BuildNumber) succeeded ($(Build.Reason)) for $(Build.RequestedFor)",
     "description" : "$(Build.SourceVersionMessage)"
     }]
  continueOnError: true

**error message in pipeline:**

##[section]Starting: ci
==============================================================================
Task         : Discord Webhook
Description  : Allows the sending of custom messages to a Discord Webhook URL
Version      : 1.6.0
Author       : Robert Burke
Help         : 
==============================================================================
##[error]Unexpected token 
 in JSON at position 106
##[section]Finishing: ci

**Comment by seraphx2** [comment]
the only thing I can think of then is you might just need to see if you can use a powershell script to manipulate the variable value and stick it in a new variae, formatted properly to work with JSON.ady I'll look at my calendar one more time and see if I can come up with something else.

**Comment by vcliment89** [comment]
I got it to work by adding one step before running powershell script like @seraphx2 suggested. YAML below:

```
- powershell: |
    $commitMessage = '$(Build.SourceVersionMessage)' -replace '\r?\n', '\n'
    Write-Output ("##vso[task.setvariable variable=build.sourceVersionMessage;]$commitMessage")
  displayName: 'PowerShell Script - Generate Variables'
```

Hope it helps

**Comment by lengyeljanos** [comment]
thank you, it is working - but only if the commit message does not contain a ' character, but visual studio automerge commit messages contain ' characters :(
